sudo: false
language: python
python:
- '3.4'
addons:
  apt:
    packages:
    - latex-xcolor
    - texlive-base
    - texlive-latex-base
    - texlive-latex-recommended
    - texlive-fonts-recommended
    - texlive-fonts-extra
    - texlive-latex-extra
    - texlive-formats-extra
    - texlive-bibtex-extra
    - texlive-humanities
    - texinfo
    - texlive-science
    - latexmk

script:
- pip install -r requirements.txt
- travis-sphinx build -s source
- make latexpdf
after_success:
- travis-sphinx deploy --cname systemshandbook.cs.luc.edu
