sudo: false
language: python
python:
- '3.4'
addons:
  apt:
    packages:
    - texlive-latex-base
    - texlive-latex-recommended
    - texlive-latex-extra
    - texlive-fonts-recommended
    - texinfo
    - mercurial
install:
- pip install sphinx
- pip install sphinx_bootstrap_theme
script:
- GH_USER=LoyolaChicagoCS GH_REPO=syshandbook "./gh-pages.sh"
env:
  global:
    secure: "EnWqNB3O/BwLxRQ6oXWuhGtp924xsnvTvE+rLvedgjA4Jaf/SxhRo8t99NBmjJsFDXWb0fUTL827cFZNA9fh2u/OXxjVUimpVJAyYXTo6FbuRWHhml1HCUxAtVWFpdjsCuTaeQxvgyjAqTYnw8cpFsxigJpDoEssW+sKOCWrtX0="
