language: python
python:
  - "3.4"
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq help2man texlive-latex-base texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texinfo
  - pip install sphinx
  - pip install sphinx_bootstrap_theme
script:
  - ./build-handbook.sh  
